import {
  TrendingUp, Globe, DollarSign, Target, Store, BarChart3, Star, Headphones, MessageCircle, Heart,
  ShoppingCart, Eye, Zap, Search, MapPin, Users, Trophy, Award, Share2, Clock, Layers, Shield, Settings,
  Database, BookOpen, FileText, LayoutGrid, Palette, PenLine, MousePointerClick, Smartphone, Tablet,
  Code, Paintbrush, BugPlay, Wrench, Mail, RefreshCw, Building2, List, Facebook, Instagram, Linkedin,
  Twitter, Youtube, Music, Image, Megaphone, Package, Fingerprint, Printer, Monitor, Calculator, Bot,
  Cpu, FolderOpen, ClipboardList, PieChart, Rocket, Lightbulb, Upload, ClipboardCheck,
  Link as LucideLink, type LucideIcon
} from "lucide-react";
import type { AccentColor, ServiceTheme } from "./types";

export const ICON_MAP: Record<string, LucideIcon> = {
  TrendingUp, Globe, DollarSign, Target, Store, BarChart3, Star, Headphones, MessageCircle, Heart,
  ShoppingCart, Eye, Zap, Search, MapPin, Users, Trophy, Award, Share2, Clock, Layers, Shield, Settings,
  Database, BookOpen, FileText, LayoutGrid, Palette, PenLine, MousePointerClick, Smartphone, Tablet,
  Code, Paintbrush, BugPlay, Wrench, Mail, RefreshCw, Building2, List, Facebook, Instagram, Linkedin,
  Twitter, Youtube, Music, Image, Megaphone, Package, Fingerprint, Printer, Monitor, Calculator, Bot,
  Cpu, FolderOpen, ClipboardList, PieChart, Rocket, Lightbulb, Upload, ClipboardCheck, Link: LucideLink,
};

export const PROCESS_ICONS: LucideIcon[] = [ClipboardList, Lightbulb, Wrench, Rocket];

export const COLOR_MAP: Record<AccentColor, ServiceTheme> = {
  indigo:  { accent: "text-indigo-600", accentBg: "bg-indigo-600", accentBgLight: "bg-indigo-50", accentBorder: "border-indigo-200", accentDark: "text-indigo-400", accentIconBg: "bg-indigo-500/20", hoverBg: "hover:bg-indigo-500", hoverBorder: "hover:border-indigo-200", hoverText: "group-hover:text-indigo-600", hoverShadow: "hover:shadow-indigo-500/10", heroBg: "bg-indigo-950", heroGlow: "rgba(99,102,241,0.45)", heroGradient: "bg-gradient-to-br from-indigo-500 via-purple-600 to-indigo-900", formButtonBg: "bg-indigo-600 hover:bg-indigo-700" },
  emerald: { accent: "text-emerald-600", accentBg: "bg-emerald-600", accentBgLight: "bg-emerald-50", accentBorder: "border-emerald-200", accentDark: "text-emerald-400", accentIconBg: "bg-emerald-500/20", hoverBg: "hover:bg-emerald-500", hoverBorder: "hover:border-emerald-200", hoverText: "group-hover:text-emerald-600", hoverShadow: "hover:shadow-emerald-500/10", heroBg: "bg-emerald-950", heroGlow: "rgba(16,185,129,0.40)", heroGradient: "bg-gradient-to-br from-emerald-500 via-teal-600 to-emerald-900", formButtonBg: "bg-emerald-600 hover:bg-emerald-700" },
  orange:  { accent: "text-orange-600", accentBg: "bg-orange-600", accentBgLight: "bg-orange-50", accentBorder: "border-orange-200", accentDark: "text-orange-400", accentIconBg: "bg-orange-500/20", hoverBg: "hover:bg-orange-500", hoverBorder: "hover:border-orange-200", hoverText: "group-hover:text-orange-600", hoverShadow: "hover:shadow-orange-500/10", heroBg: "bg-orange-950", heroGlow: "rgba(234,88,12,0.45)", heroGradient: "bg-gradient-to-br from-orange-400 via-pink-600 to-rose-900", formButtonBg: "bg-orange-600 hover:bg-orange-700" },
  violet:  { accent: "text-violet-600", accentBg: "bg-violet-600", accentBgLight: "bg-violet-50", accentBorder: "border-violet-200", accentDark: "text-violet-400", accentIconBg: "bg-violet-500/20", hoverBg: "hover:bg-violet-500", hoverBorder: "hover:border-violet-200", hoverText: "group-hover:text-violet-600", hoverShadow: "hover:shadow-violet-500/10", heroBg: "bg-violet-950", heroGlow: "rgba(124,58,237,0.45)", heroGradient: "bg-gradient-to-br from-violet-500 via-purple-600 to-indigo-900", formButtonBg: "bg-violet-600 hover:bg-violet-700" },
  pink:    { accent: "text-pink-600", accentBg: "bg-pink-600", accentBgLight: "bg-pink-50", accentBorder: "border-pink-200", accentDark: "text-pink-400", accentIconBg: "bg-pink-500/20", hoverBg: "hover:bg-pink-500", hoverBorder: "hover:border-pink-200", hoverText: "group-hover:text-pink-600", hoverShadow: "hover:shadow-pink-500/10", heroBg: "bg-pink-950", heroGlow: "rgba(219,39,119,0.45)", heroGradient: "bg-gradient-to-br from-pink-500 via-rose-600 to-purple-900", formButtonBg: "bg-pink-600 hover:bg-pink-700" },
  fuchsia: { accent: "text-fuchsia-600", accentBg: "bg-fuchsia-600", accentBgLight: "bg-fuchsia-50", accentBorder: "border-fuchsia-200", accentDark: "text-fuchsia-400", accentIconBg: "bg-fuchsia-500/20", hoverBg: "hover:bg-fuchsia-500", hoverBorder: "hover:border-fuchsia-200", hoverText: "group-hover:text-fuchsia-600", hoverShadow: "hover:shadow-fuchsia-500/10", heroBg: "bg-fuchsia-950", heroGlow: "rgba(192,38,211,0.45)", heroGradient: "bg-gradient-to-br from-fuchsia-500 via-pink-600 to-rose-900", formButtonBg: "bg-fuchsia-600 hover:bg-fuchsia-700" },
  teal:    { accent: "text-teal-600", accentBg: "bg-teal-600", accentBgLight: "bg-teal-50", accentBorder: "border-teal-200", accentDark: "text-teal-400", accentIconBg: "bg-teal-500/20", hoverBg: "hover:bg-teal-500", hoverBorder: "hover:border-teal-200", hoverText: "group-hover:text-teal-600", hoverShadow: "hover:shadow-teal-500/10", heroBg: "bg-teal-950", heroGlow: "rgba(13,148,136,0.45)", heroGradient: "bg-gradient-to-br from-teal-400 via-emerald-600 to-cyan-900", formButtonBg: "bg-teal-600 hover:bg-teal-700" },
  sky:     { accent: "text-sky-600", accentBg: "bg-sky-600", accentBgLight: "bg-sky-50", accentBorder: "border-sky-200", accentDark: "text-sky-400", accentIconBg: "bg-sky-500/20", hoverBg: "hover:bg-sky-500", hoverBorder: "hover:border-sky-200", hoverText: "group-hover:text-sky-600", hoverShadow: "hover:shadow-sky-500/10", heroBg: "bg-sky-950", heroGlow: "rgba(2,132,199,0.45)", heroGradient: "bg-gradient-to-br from-sky-400 via-blue-600 to-indigo-900", formButtonBg: "bg-sky-600 hover:bg-sky-700" },
  cyan:    { accent: "text-cyan-600", accentBg: "bg-cyan-600", accentBgLight: "bg-cyan-50", accentBorder: "border-cyan-200", accentDark: "text-cyan-400", accentIconBg: "bg-cyan-500/20", hoverBg: "hover:bg-cyan-500", hoverBorder: "hover:border-cyan-200", hoverText: "group-hover:text-cyan-600", hoverShadow: "hover:shadow-cyan-500/10", heroBg: "bg-cyan-950", heroGlow: "rgba(8,145,178,0.45)", heroGradient: "bg-gradient-to-br from-cyan-400 via-teal-600 to-blue-900", formButtonBg: "bg-cyan-600 hover:bg-cyan-700" },
  amber:   { accent: "text-amber-600", accentBg: "bg-amber-600", accentBgLight: "bg-amber-50", accentBorder: "border-amber-200", accentDark: "text-amber-400", accentIconBg: "bg-amber-500/20", hoverBg: "hover:bg-amber-500", hoverBorder: "hover:border-amber-200", hoverText: "group-hover:text-amber-600", hoverShadow: "hover:shadow-amber-500/10", heroBg: "bg-amber-950", heroGlow: "rgba(217,119,6,0.50)", heroGradient: "bg-gradient-to-br from-amber-400 via-orange-500 to-rose-800", formButtonBg: "bg-amber-600 hover:bg-amber-700" },
  rose:    { accent: "text-rose-600", accentBg: "bg-rose-600", accentBgLight: "bg-rose-50", accentBorder: "border-rose-200", accentDark: "text-rose-400", accentIconBg: "bg-rose-500/20", hoverBg: "hover:bg-rose-500", hoverBorder: "hover:border-rose-200", hoverText: "group-hover:text-rose-600", hoverShadow: "hover:shadow-rose-500/10", heroBg: "bg-rose-950", heroGlow: "rgba(225,29,72,0.50)", heroGradient: "bg-gradient-to-br from-rose-500 via-pink-600 to-purple-900", formButtonBg: "bg-rose-600 hover:bg-rose-700" },
  purple:  { accent: "text-purple-600", accentBg: "bg-purple-600", accentBgLight: "bg-purple-50", accentBorder: "border-purple-200", accentDark: "text-purple-400", accentIconBg: "bg-purple-500/20", hoverBg: "hover:bg-purple-500", hoverBorder: "hover:border-purple-200", hoverText: "group-hover:text-purple-600", hoverShadow: "hover:shadow-purple-500/10", heroBg: "bg-purple-950", heroGlow: "rgba(147,51,234,0.45)", heroGradient: "bg-gradient-to-br from-purple-500 via-fuchsia-600 to-indigo-900", formButtonBg: "bg-purple-600 hover:bg-purple-700" },
};
